name: Expressjs Build

on:
  push:
    branches: main
    paths: 
    - 'api/**'

jobs:
  main:
    runs-on: Ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ahlem11964649
          password: dckr_pat_KxgsT00FynaqDD8dc8XdrC6A4Po

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: api/.
          file: api/Dockerfile
          push: true
          tags: ahlem11964649/mean-expressjs:latest
          secrets: |
            GIT_AUTH_TOKEN=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
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
